"""comments edited

Revision ID: 484403d45d6f
Revises: f6ccb89441dc
Create Date: 2024-08-25 00:41:09.164724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484403d45d6f'
down_revision: Union[str, None] = 'f6ccb89441dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_author_id_fkey', 'comments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('comments_author_id_fkey', 'comments', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
