"""houses added

Revision ID: d9e1d9348d01
Revises: 3fd7ae6327c4
Create Date: 2024-08-22 23:42:47.992721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e1d9348d01'
down_revision: Union[str, None] = '3fd7ae6327c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'houses', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'owner_id')
    # ### end Alembic commands ###
